# specify language
language:
  - python

# specify python version(s)
python:
  - "3.4"
  - "2.7"

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - nosetests

# deploy
deploy:
  provider: heroku
  api_key:
    secure: XEtRjqqP6ZgiZKDi/OjSyMhJIPVPUzmX+5899LXfm2eyMtItYqFouCtBAOmBU5bWnZiwgXdB9l9ra2yiC+321TET1WVJe1WHDTFW1rzIpWS7t/ZIJYPhmwcYxa02kzLQZsrDZH/BW/cUuoHlOhmGSpuqO6SO1h1XnzwqHVe68vw=
  app: flasktaskr
  on:
    branch: master
    python: '3.4'
    repo: realpython/flasktaskr_project